name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Latest stable version

    - name: Setup Node.js
      uses: actions/setup-node@v4 # Use Node.js 20 or later
      with:
        node-version: '20'

    - name: Log in to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v2 # Ensure you use the latest version
      with:
        registry-type: private # Make sure this matches your ECR setup
        role-arn: ${{ secrets.AWS_ROLE_ARN }} # Use your IAM role ARN here
      env:
        AWS_REGION: ap-southeast-1

    - name: Build Docker image
      env:
        ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-southeast-1.amazonaws.com
        ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        echo "IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

    - name: Push Docker image to Amazon ECR
      run: |
        docker push ${{ env.IMAGE_URI }}

    - name: Register ECS Task Definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: hello-world-task.json
        container-name: hello-world-app
        image: ${{ env.IMAGE_URI }}

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        cluster: hello-world-cluster
        service: hello-world-service
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        wait-for-service-stability: true
      env:
        AWS_REGION: ap-southeast-1








